#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

PASSWORD=${SSH_PASSWORD:-$(openssl passwd -crypt secret)}

if [ -n "$HOSTED" ]; then
	usermod -l cloudestuary www-data || true
  groupmod -n cloudestuary www-data || true
  usermod -d /var/www -s /bin/bash -m cloudestuary || true
else
	PUID=${PUID:-1000}
	PGID=${PGID:-1000}

	groupadd -g $PGID cloudestuary
	useradd -u $PUID -g cloudestuary -m cloudestuary -s /bin/bash -d /var/www
fi

echo 'cloudestuary:'$PASSWORD | chpasswd -e

chown -R cloudestuary:cloudestuary /var/www

exec "$@"
